cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
cat lol.c | cat 
